services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: money_db
      POSTGRES_USER: money_user
      POSTGRES_PASSWORD: money_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@money.com
      PGADMIN_DEFAULT_PASSWORD: money
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
