[project]
name = "money"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "gunicorn>=23.0.0",
    "iso4217>=1.14.20250512",
    "psycopg[binary]>=3.2.10",
    "python-dotenv>=1.1.1",
]
