# Generated by Django 5.2.5 on 2025-12-15 02:45

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, default=accounts.models.get_default_currency, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency'),
        ),
    ]
