# Generated by Django 5.2.5 on 2025-12-15 02:54

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_currency'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=accounts.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
