# Generated by Django 5.2.5 on 2025-11-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_date_time_alter_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='paymentType',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('card', 'Card'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='typeRecord',
            field=models.CharField(choices=[('expense', 'Expense'), ('transfer', 'Transfer'), ('income', 'Income'), ('investment', 'Investment')], max_length=20),
        ),
    ]
