# Generated by Django 5.2.5 on 2025-12-15 02:54

import django.db.models.deletion
import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('records', '0003_alter_record_paymenttype_alter_record_typerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='currency',
            field=models.ForeignKey(default=records.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
    ]
