# Generated by Django 5.2.5 on 2025-12-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_currency'),
        ('records', '0004_alter_record_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='record',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
