# Generated by Django 5.2.5 on 2025-12-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_currency'),
        ('records', '0005_record_from_account_record_to_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.account'),
        ),
    ]
